# LambdaTest Configuration

# Project and folder configuration
project_id: "01J87QEHKVYWMP0W5E8K5CMXRA"
folder_id: "01J87QEHMHFXWC40A758WRX3NR"

# Test Run configuration
assignee: 3201243
environment_id: 238648

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
